version: 2
project_name: iptv-proxy

builds:
  - binary: iptv-proxy
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor
      - -a
    goos:
      - windows
    goarch:
      - amd64

archives:
  - format_overrides:
     - goos: windows
       formats: [ 'zip' ]

release:
  github:
    owner: MatAnzPL
    name: iptv-proxy-yagoor
  draft: false
